spring:
  name: notification-service
  kafka:
    consumer:
      group-id: default
    #    producer:
    #      key-serializer: org.apache.common.serialization.StringSerializer
    #      value-serializer: org.springframework.kafka.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

server:
  port: 0


eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka


sendgrid:
  key:
  sender:



support:
  email:
    enable: true
    recipient: eliyaakiva1@gmail.com
  email-interval: 21600