

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: Eliya229978
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-auth-service
    jwt:
      token-expiration-after-days: 2
      token-prefix: Bearer
      private-secret-key: qwertyuiopasdfghjklzxcvbnm123456ghh4t4y34tf

eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka

server:
  port: 0


management:
  endpoints:
    web:
      exposure:
        include: prometheus