spring:
    name: notification-service
  kafka:
    consumer:
      key-deserializer: org.apache.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.serializer.JsonDeserializer
      group-id: notificationId
    bootstrap-servers: localhost:9092
server:
  port: 0


eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka