
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: Eliya229978
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: default
#    producer:
#      key-serializer: org.apache.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
    template:
      default-topic: notification-topic
server:
  port: 0


eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka



management:
  endpoints:
    web:
      exposure:
        include: prometheus